#!/bin/bash
export PATH=$HOME/bin:/usr/local/bin:$PATH
PROJECT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$PROJECT"
git clone https://github.com/solcery/solcery_cms.git
cd solcery_cms
git fetch
git checkout main
brew install yarn
brew install node
yarn
yarn start