#!/bin/bash
PROJECT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
docker-compose -f "$PROJECT"/docker-compose.yaml build
docker-compose -f "$PROJECT"/docker-compose.yaml up -d
open http://localhost:8080/
exit 0